# Generated by Django 3.1.2 on 2021-08-19 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210302_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.CharField(max_length=6)),
                ('owner', models.CharField(choices=[('RSP', 'Rameshbhai'), ('MRP', 'Madhuben'), ('JRP', 'Jaykrushna'), ('YRP', 'Yash'), ('DSP', 'Dahyabhai'), ('ADP', 'Anandiben'), ('GDP', 'Ghanshyam'), ('KDP', 'Kamal'), ('AKP', 'Ankita'), ('SVPHUF', 'Somabhai HUF'), ('RSPHUF', 'Rameshbhai HUF'), ('DSPHUF', 'Dahyabhai HUF')], default='RSP', max_length=6)),
                ('area', models.FloatField()),
                ('light', models.IntegerField(max_length=6)),
                ('tax', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('PAN', models.CharField(max_length=10, unique=True)),
                ('aadhar', models.IntegerField(max_length=10, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for lease', primary_key=True, serialize=False)),
                ('start', models.DateField(help_text='Start date of the lease')),
                ('end', models.DateField(help_text='End date of the Lease')),
                ('rent', models.FloatField(help_text='Monthly Rent')),
                ('security', models.FloatField(help_text='Security Deposit one time payment at the start')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='catalog.property')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='catalog.tenant')),
            ],
        ),
    ]
