# Generated by Django 3.1.2 on 2021-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_lease_property_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='property',
            name='light',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='aadhar',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
