# Generated by Django 3.1.2 on 2021-08-19 09:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210819_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each entry', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Db', 'Debit'), ('Cr', 'Credit')], max_length=5)),
                ('amount', models.FloatField()),
                ('Note', models.CharField(max_length=50)),
            ],
        ),
    ]
